no_initseg: False
inner_outer: False
leader_test_env: True
checkpoint_path: "drone_game_contextual_default"
log_wandb: True

env: "drone_game"
env_config:
  width: 22
  height: 22
  drone_dist: 5
  agent_view_size: 3
  leader_cont: False
  follower_blind: True
  video_name: "size6_context_drone0.avi"

algo: "ppo"
algo_config:
  follower:
    use_lr_scheduler: False
    start_lr: 1.0e-3
    end_lr: 1.0e-5
    gamma: 0.95
    ent_coef: 0.0
    batch_size: 180
    n_steps: 180
  leader:
