no_initseg: False
inner_outer: False
leader_test_env: False
checkpoint_path: "drone_game_contextual"
log_wandb: False

env: "drone_game"
env_config:
  width: 12
  height: 12
  drone_dist: 5
  leader_cont: True
  video_name: "size6_context_drone0.avi"

algo: "ppo"
algo_config:
  follower:
    use_lr_scheduler: True
    start_lr: 1.0e-3
    end_lr: 1.0e-5
    gamma: 0.95
    ent_coef: 0.0
    batch_size: 180
    n_steps: 180
  leader:
